[package]
name = "rmc"
version = "0.2.0"
authors = ["Oleksiy Slyshyk <alexslyshyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs-err = "2.5"
bstr = "0.2"
